changesetBaseRefs:
  - main
  - upstream/main
  - origin/main

compressionLevel: mixed

enableHardenedMode: false

initScope: uppy

nodeLinker: node-modules

npmMinimalAgeGate: 1w

npmPublishAccess: public
