name: 🚀 Feature request
labels: Feature
description: Suggest an idea
body:
  - type: checkboxes
    id: initial-checklist
    attributes:
      label: Initial checklist
      options:
        - label:
            I understand this is a feature request and questions should be
            posted in the [Community Forum](https://community.transloadit.com/)
          required: true
        - label:
            I searched
            [issues](https://github.com/transloadit/uppy/issues?q=is%3Aissue)
            and couldn’t find anything (or linked relevant results below)
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Please describe the problem you are trying to solve here.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What should happen? Please describe the desired behavior.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description:
        What are the alternative solutions? Can this be solved in a different
        way?
    validations:
      required: true
