// export { default as Dashboard } from './lib/Dashboard.vue.js'
// export { default as DashboardModal } from './lib/DashboardModal.vue.js'
// export { default as DragDrop } from './lib/DragDrop.vue.js'
// export { default as ProgressBar } from './lib/ProgressBar.vue.js'
// export { default as StatusBar } from './lib/StatusBar.vue.js'
export { default as Dashboard } from './src/Dashboard.vue'
export { default as DashboardModal } from './src/DashboardModal.vue'
export { default as DragDrop } from './src/DragDrop.vue'
export { default as ProgressBar } from './src/ProgressBar.vue'
export { default as StatusBar } from './src/StatusBar.vue'
