// Attributes in the format of htmlAtrribute: reactAttribute
const possibleStandardNames = [
  'accept',
  'acceptCharset',
  'acceptCharset',
  'accessKey',
  'action',
  'allowFullScreen',
  'alt',
  'as',
  'async',
  'autoCapitalize',
  'autoComplete',
  'autoCorrect',
  'autoFocus',
  'autoPlay',
  'autoSave',
  'capture',
  'cellPadding',
  'cellSpacing',
  'challenge',
  'charSet',
  'checked',
  'children',
  'cite',
  'className',
  'classID',
  'className',
  'cols',
  'colSpan',
  'content',
  'contentEditable',
  'contextMenu',
  'controls',
  'controlsList',
  'coords',
  'crossOrigin',
  'dangerouslySetInnerHTML',
  'data',
  'dateTime',
  'default',
  'defaultChecked',
  'defaultValue',
  'defer',
  'dir',
  'disabled',
  'disablePictureInPicture',
  'disableRemotePlayback',
  'download',
  'draggable',
  'encType',
  'enterKeyHint',
  'htmlFor',
  'form',
  'formMethod',
  'formAction',
  'formEncType',
  'formNoValidate',
  'formTarget',
  'frameBorder',
  'headers',
  // 'height',
  'hidden',
  'high',
  'href',
  'hrefLang',
  'htmlFor',
  'httpEquiv',
  'httpEquiv',
  'icon',
  'id',
  'innerHTML',
  'inputMode',
  'integrity',
  'is',
  'itemID',
  'itemProp',
  'itemRef',
  'itemScope',
  'itemType',
  'keyParams',
  'keyType',
  'kind',
  'label',
  'lang',
  'list',
  'loop',
  'low',
  'manifest',
  'marginWidth',
  'marginHeight',
  'max',
  'maxLength',
  'media',
  'mediaGroup',
  'method',
  'min',
  'minLength',
  'multiple',
  'muted',
  'name',
  'noModule',
  'nonce',
  'noValidate',
  'open',
  'optimum',
  'pattern',
  'placeholder',
  'playsInline',
  'poster',
  'preload',
  'profile',
  'radioGroup',
  'readOnly',
  'referrerPolicy',
  'rel',
  'required',
  'reversed',
  'role',
  'rows',
  'rowSpan',
  'sandbox',
  'scope',
  'scoped',
  'scrolling',
  'seamless',
  'selected',
  'shape',
  'size',
  'sizes',
  'span',
  'spellCheck',
  'src',
  'srcDoc',
  'srcLang',
  'srcSet',
  'start',
  'step',
  'style',
  'summary',
  'tabIndex',
  // 'target',
  'title',
  'type',
  'useMap',
  'value',
  // 'width',
  'wmode',
  'wrap',
]

// A decent polyfill for Object.entries for good browser support
const getEntries = (object) => {
  // eslint-disable-next-line compat/compat
  return Object.entries ? Object.entries(object) : Object.keys(object).map(key => [key, object[key]])
}

const getHTMLProps = (props) => {
  // Gets all the React props
  const reducer = (acc, [key, value]) => (possibleStandardNames.includes(key) ? { ...acc, [key]: value } : acc)
  return getEntries(props).reduce(reducer, {})
}

module.exports = getHTMLProps
