name: Lockfile checks

on:
  push:
    branches: [main]
    paths:
      - pnpm-lock.yaml
  pull_request:
    # We want all branches so we configure types to be the GH default again
    types: [opened, synchronize, reopened]
    paths:
      - pnpm-lock.yaml

env:
  PNPM_HOME: /tmp/pnpm

jobs:
  lint_lockfile:
    name: Lint pnpm-lock.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: corepack pnpm install --frozen-lockfile